// Generated by https://quicktype.io

import { Route, UrlSegment, UrlTree } from "@angular/router";
import { Observable } from "rxjs";

export interface User {
  id:    number;
  user:  string;
  email: string;
}


